controller_list:
  - name: fake_ur3_controller
    joints:
      - ur3_shoulder_pan_joint
      - ur3_shoulder_lift_joint
      - ur3_elbow_joint
      - ur3_wrist_1_joint
      - ur3_wrist_2_joint
      - ur3_wrist_3_joint
  - name: fake_ur10_controller
    joints:
      - ur10_shoulder_pan_joint
      - ur10_shoulder_lift_joint
      - ur10_elbow_joint
      - ur10_wrist_1_joint
      - ur10_wrist_2_joint
      - ur10_wrist_3_joint
  - name: fake_ur3_ur10_controller
    joints:
      - ur10_shoulder_pan_joint
      - ur10_shoulder_lift_joint
      - ur10_elbow_joint
      - ur10_wrist_1_joint
      - ur10_wrist_2_joint
      - ur10_wrist_3_joint
      - ur3_shoulder_pan_joint
      - ur3_shoulder_lift_joint
      - ur3_elbow_joint
      - ur3_wrist_1_joint
      - ur3_wrist_2_joint
      - ur3_wrist_3_joint
  - name: fake_spoon_gripper_controller
    joints:
      []
  - name: fake_ur10_with_gripper_controller
    joints:
      - ur10_shoulder_pan_joint
      - ur10_shoulder_lift_joint
      - ur10_elbow_joint
      - ur10_wrist_1_joint
      - ur10_wrist_2_joint
      - ur10_wrist_3_joint
  - name: fake_ag95_gripper_controller
    joints:
      - grip_tip_joint
  - name: fake_ur3_with_gripper_controller
    joints:
      - ur3_shoulder_pan_joint
      - ur3_shoulder_lift_joint
      - ur3_elbow_joint
      - ur3_wrist_1_joint
      - ur3_wrist_2_joint
      - ur3_wrist_3_joint
      - grip_tip_joint
  - name: fake_all_controller
    joints:
      - ur10_shoulder_pan_joint
      - ur10_shoulder_lift_joint
      - ur10_elbow_joint
      - ur10_wrist_1_joint
      - ur10_wrist_2_joint
      - ur10_wrist_3_joint
      - ur3_shoulder_pan_joint
      - ur3_shoulder_lift_joint
      - ur3_elbow_joint
      - ur3_wrist_1_joint
      - ur3_wrist_2_joint
      - ur3_wrist_3_joint
      - grip_tip_joint