set(_CATKIN_CURRENT_PACKAGE "spoon_metal_own")
set(spoon_metal_own_VERSION "1.0.0")
set(spoon_metal_own_MAINTAINER " <TODO@email.com>")
set(spoon_metal_own_PACKAGE_FORMAT "2")
set(spoon_metal_own_BUILD_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher_gui" "gazebo")
set(spoon_metal_own_BUILD_EXPORT_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher_gui" "gazebo")
set(spoon_metal_own_BUILDTOOL_DEPENDS "catkin")
set(spoon_metal_own_BUILDTOOL_EXPORT_DEPENDS )
set(spoon_metal_own_EXEC_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher_gui" "gazebo")
set(spoon_metal_own_RUN_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher_gui" "gazebo")
set(spoon_metal_own_TEST_DEPENDS )
set(spoon_metal_own_DOC_DEPENDS )
set(spoon_metal_own_URL_WEBSITE "")
set(spoon_metal_own_URL_BUGTRACKER "")
set(spoon_metal_own_URL_REPOSITORY "")
set(spoon_metal_own_DEPRECATED "")