# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dig_dish.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dig_dish_Form(object):
    def setupUi(self, Dig_dish_Form):
        Dig_dish_Form.setObjectName("Dig_dish_Form")
        Dig_dish_Form.resize(755, 600)
        self.order_list_text = QtWidgets.QTextBrowser(Dig_dish_Form)
        self.order_list_text.setGeometry(QtCore.QRect(440, 50, 301, 301))
        self.order_list_text.setObjectName("order_list_text")
        self.dig_show_label = QtWidgets.QLabel(Dig_dish_Form)
        self.dig_show_label.setGeometry(QtCore.QRect(20, 50, 400, 300))
        self.dig_show_label.setStyleSheet("border-width: 2px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.dig_show_label.setText("")
        self.dig_show_label.setObjectName("dig_show_label")
        self.label = QtWidgets.QLabel(Dig_dish_Form)
        self.label.setGeometry(QtCore.QRect(140, 10, 111, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("color:white;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dig_dish_Form)
        self.label_2.setGeometry(QtCore.QRect(450, 10, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("color:white;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.label_2.setObjectName("label_2")
        self.clear_dig_txt = QtWidgets.QPushButton(Dig_dish_Form)
        self.clear_dig_txt.setGeometry(QtCore.QRect(550, 10, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.clear_dig_txt.setFont(font)
        self.clear_dig_txt.setStyleSheet("color:white;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.clear_dig_txt.setObjectName("clear_dig_txt")
        self.save_dig_txt = QtWidgets.QPushButton(Dig_dish_Form)
        self.save_dig_txt.setGeometry(QtCore.QRect(650, 10, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.save_dig_txt.setFont(font)
        self.save_dig_txt.setStyleSheet("color:white;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.save_dig_txt.setObjectName("save_dig_txt")
        self.groupBox = QtWidgets.QGroupBox(Dig_dish_Form)
        self.groupBox.setGeometry(QtCore.QRect(460, 410, 271, 160))
        self.groupBox.setObjectName("groupBox")
        self.resume_dig_button = QtWidgets.QPushButton(self.groupBox)
        self.resume_dig_button.setGeometry(QtCore.QRect(140, 100, 110, 38))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.resume_dig_button.setFont(font)
        self.resume_dig_button.setStyleSheet("color:gray;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.resume_dig_button.setIconSize(QtCore.QSize(16, 16))
        self.resume_dig_button.setCheckable(False)
        self.resume_dig_button.setObjectName("resume_dig_button")
        self.stop_dig_button = QtWidgets.QPushButton(self.groupBox)
        self.stop_dig_button.setGeometry(QtCore.QRect(10, 100, 110, 38))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.stop_dig_button.setFont(font)
        self.stop_dig_button.setStyleSheet("color:gray;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.stop_dig_button.setIconSize(QtCore.QSize(16, 16))
        self.stop_dig_button.setCheckable(False)
        self.stop_dig_button.setObjectName("stop_dig_button")
        self.dig_dish_start_button = QtWidgets.QPushButton(self.groupBox)
        self.dig_dish_start_button.setGeometry(QtCore.QRect(10, 40, 110, 38))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dig_dish_start_button.setFont(font)
        self.dig_dish_start_button.setStyleSheet("color:gray;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.dig_dish_start_button.setIconSize(QtCore.QSize(16, 16))
        self.dig_dish_start_button.setCheckable(False)
        self.dig_dish_start_button.setObjectName("dig_dish_start_button")
        self.dig_dish_end_button = QtWidgets.QPushButton(self.groupBox)
        self.dig_dish_end_button.setGeometry(QtCore.QRect(140, 40, 110, 38))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dig_dish_end_button.setFont(font)
        self.dig_dish_end_button.setStyleSheet("color:gray;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.dig_dish_end_button.setIconSize(QtCore.QSize(16, 16))
        self.dig_dish_end_button.setCheckable(False)
        self.dig_dish_end_button.setObjectName("dig_dish_end_button")
        self.current_menu_list = QtWidgets.QListView(Dig_dish_Form)
        self.current_menu_list.setGeometry(QtCore.QRect(20, 410, 111, 101))
        self.current_menu_list.setObjectName("current_menu_list")
        self.label_3 = QtWidgets.QLabel(Dig_dish_Form)
        self.label_3.setGeometry(QtCore.QRect(30, 370, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setStyleSheet("color:white;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.label_3.setObjectName("label_3")
        self.groupBox_2 = QtWidgets.QGroupBox(Dig_dish_Form)
        self.groupBox_2.setGeometry(QtCore.QRect(150, 410, 271, 160))
        self.groupBox_2.setObjectName("groupBox_2")
        self.acquire_order_button = QtWidgets.QPushButton(self.groupBox_2)
        self.acquire_order_button.setGeometry(QtCore.QRect(150, 100, 110, 38))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.acquire_order_button.setFont(font)
        self.acquire_order_button.setStyleSheet("color:lightblue;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.acquire_order_button.setIconSize(QtCore.QSize(16, 16))
        self.acquire_order_button.setCheckable(False)
        self.acquire_order_button.setObjectName("acquire_order_button")
        self.updata_menu_button = QtWidgets.QPushButton(self.groupBox_2)
        self.updata_menu_button.setGeometry(QtCore.QRect(10, 40, 110, 38))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.updata_menu_button.setFont(font)
        self.updata_menu_button.setStyleSheet("color:white;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.updata_menu_button.setObjectName("updata_menu_button")
        self.dig_choose_dish_button = QtWidgets.QPushButton(self.groupBox_2)
        self.dig_choose_dish_button.setGeometry(QtCore.QRect(10, 100, 110, 38))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dig_choose_dish_button.setFont(font)
        self.dig_choose_dish_button.setStyleSheet("color:gray;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.dig_choose_dish_button.setObjectName("dig_choose_dish_button")
        self.add_bowl_button = QtWidgets.QPushButton(self.groupBox_2)
        self.add_bowl_button.setGeometry(QtCore.QRect(150, 40, 110, 38))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.add_bowl_button.setFont(font)
        self.add_bowl_button.setStyleSheet("color:gray;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.add_bowl_button.setIconSize(QtCore.QSize(16, 16))
        self.add_bowl_button.setCheckable(False)
        self.add_bowl_button.setObjectName("add_bowl_button")
        self.bowl_num_input = QtWidgets.QSpinBox(Dig_dish_Form)
        self.bowl_num_input.setGeometry(QtCore.QRect(20, 560, 111, 27))
        self.bowl_num_input.setObjectName("bowl_num_input")
        self.label_4 = QtWidgets.QLabel(Dig_dish_Form)
        self.label_4.setGeometry(QtCore.QRect(30, 520, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setStyleSheet("color:white;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dig_dish_Form)
        QtCore.QMetaObject.connectSlotsByName(Dig_dish_Form)

    def retranslateUi(self, Dig_dish_Form):
        _translate = QtCore.QCoreApplication.translate
        Dig_dish_Form.setWindowTitle(_translate("Dig_dish_Form", "Form"))
        self.label.setText(_translate("Dig_dish_Form", "     相机画面"))
        self.label_2.setText(_translate("Dig_dish_Form", "  Note"))
        self.clear_dig_txt.setText(_translate("Dig_dish_Form", "Clear"))
        self.save_dig_txt.setText(_translate("Dig_dish_Form", "Save"))
        self.groupBox.setTitle(_translate("Dig_dish_Form", "控制"))
        self.resume_dig_button.setText(_translate("Dig_dish_Form", "恢复打菜"))
        self.stop_dig_button.setText(_translate("Dig_dish_Form", "暂停打菜"))
        self.dig_dish_start_button.setText(_translate("Dig_dish_Form", "开始打菜"))
        self.dig_dish_end_button.setText(_translate("Dig_dish_Form", "结束打菜"))
        self.label_3.setText(_translate("Dig_dish_Form", "  当前菜单"))
        self.groupBox_2.setTitle(_translate("Dig_dish_Form", "手动操作"))
        self.acquire_order_button.setText(_translate("Dig_dish_Form", "查询订单"))
        self.updata_menu_button.setText(_translate("Dig_dish_Form", "更新菜单"))
        self.dig_choose_dish_button.setText(_translate("Dig_dish_Form", "打取"))
        self.add_bowl_button.setText(_translate("Dig_dish_Form", "补碗操作"))
        self.label_4.setText(_translate("Dig_dish_Form", "  碗的数量"))

