# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'generate_menu.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Menu_Form(object):
    def setupUi(self, Menu_Form):
        Menu_Form.setObjectName("Menu_Form")
        Menu_Form.resize(755, 600)
        self.menu_message_text = QtWidgets.QTextBrowser(Menu_Form)
        self.menu_message_text.setGeometry(QtCore.QRect(440, 50, 301, 301))
        self.menu_message_text.setObjectName("menu_message_text")
        self.menu_label = QtWidgets.QLabel(Menu_Form)
        self.menu_label.setGeometry(QtCore.QRect(20, 50, 400, 300))
        self.menu_label.setStyleSheet("border-width: 2px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.menu_label.setText("")
        self.menu_label.setObjectName("menu_label")
        self.label = QtWidgets.QLabel(Menu_Form)
        self.label.setGeometry(QtCore.QRect(140, 10, 131, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("color:white;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Menu_Form)
        self.label_2.setGeometry(QtCore.QRect(450, 10, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("color:white;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.label_2.setObjectName("label_2")
        self.clear_menu_txt = QtWidgets.QPushButton(Menu_Form)
        self.clear_menu_txt.setGeometry(QtCore.QRect(550, 10, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.clear_menu_txt.setFont(font)
        self.clear_menu_txt.setStyleSheet("color:white;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.clear_menu_txt.setObjectName("clear_menu_txt")
        self.save_menu_txt = QtWidgets.QPushButton(Menu_Form)
        self.save_menu_txt.setGeometry(QtCore.QRect(650, 10, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.save_menu_txt.setFont(font)
        self.save_menu_txt.setStyleSheet("color:white;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.save_menu_txt.setObjectName("save_menu_txt")
        self.generate_menu_button = QtWidgets.QPushButton(Menu_Form)
        self.generate_menu_button.setGeometry(QtCore.QRect(630, 440, 99, 38))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.generate_menu_button.setFont(font)
        self.generate_menu_button.setStyleSheet("color:gray;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.generate_menu_button.setIconSize(QtCore.QSize(16, 16))
        self.generate_menu_button.setCheckable(False)
        self.generate_menu_button.setObjectName("generate_menu_button")
        self.groupBox = QtWidgets.QGroupBox(Menu_Form)
        self.groupBox.setGeometry(QtCore.QRect(340, 370, 271, 211))
        self.groupBox.setObjectName("groupBox")
        self.auto_mode = QtWidgets.QRadioButton(self.groupBox)
        self.auto_mode.setGeometry(QtCore.QRect(30, 40, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.auto_mode.setFont(font)
        self.auto_mode.setObjectName("auto_mode")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(30, 150, 81, 25))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(29, 100, 81, 25))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.move_frequency_input = QtWidgets.QLineEdit(self.groupBox)
        self.move_frequency_input.setGeometry(QtCore.QRect(120, 100, 113, 30))
        self.move_frequency_input.setObjectName("move_frequency_input")
        self.move_interval_input = QtWidgets.QLineEdit(self.groupBox)
        self.move_interval_input.setGeometry(QtCore.QRect(120, 150, 113, 30))
        self.move_interval_input.setObjectName("move_interval_input")
        self.start_scan_button = QtWidgets.QPushButton(self.groupBox)
        self.start_scan_button.setGeometry(QtCore.QRect(140, 40, 99, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.start_scan_button.setFont(font)
        self.start_scan_button.setStyleSheet("color:gray;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.start_scan_button.setIconSize(QtCore.QSize(16, 16))
        self.start_scan_button.setCheckable(False)
        self.start_scan_button.setObjectName("start_scan_button")
        self.groupBox_2 = QtWidgets.QGroupBox(Menu_Form)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 370, 281, 211))
        self.groupBox_2.setObjectName("groupBox_2")
        self.manual_mode = QtWidgets.QRadioButton(self.groupBox_2)
        self.manual_mode.setGeometry(QtCore.QRect(20, 40, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.manual_mode.setFont(font)
        self.manual_mode.setObjectName("manual_mode")
        self.car_forward_copy = Car_Forward_button(self.groupBox_2)
        self.car_forward_copy.setGeometry(QtCore.QRect(20, 100, 99, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.car_forward_copy.setFont(font)
        self.car_forward_copy.setStyleSheet("color:gray;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.car_forward_copy.setObjectName("car_forward_copy")
        self.car_back_copy = Car_Backward_button(self.groupBox_2)
        self.car_back_copy.setGeometry(QtCore.QRect(140, 100, 99, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.car_back_copy.setFont(font)
        self.car_back_copy.setStyleSheet("color:gray;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.car_back_copy.setObjectName("car_back_copy")
        self.reco_dish_button = QtWidgets.QPushButton(self.groupBox_2)
        self.reco_dish_button.setGeometry(QtCore.QRect(140, 40, 99, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.reco_dish_button.setFont(font)
        self.reco_dish_button.setStyleSheet("color:gray;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.reco_dish_button.setIconSize(QtCore.QSize(16, 16))
        self.reco_dish_button.setCheckable(False)
        self.reco_dish_button.setObjectName("reco_dish_button")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(30, 150, 81, 25))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.dish_location_input = QtWidgets.QLineEdit(self.groupBox_2)
        self.dish_location_input.setGeometry(QtCore.QRect(130, 150, 113, 30))
        self.dish_location_input.setObjectName("dish_location_input")
        self.save_menu_button = QtWidgets.QPushButton(Menu_Form)
        self.save_menu_button.setGeometry(QtCore.QRect(630, 490, 99, 38))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.save_menu_button.setFont(font)
        self.save_menu_button.setStyleSheet("color:gray;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.save_menu_button.setIconSize(QtCore.QSize(16, 16))
        self.save_menu_button.setCheckable(False)
        self.save_menu_button.setObjectName("save_menu_button")
        self.upload_menu_button = QtWidgets.QPushButton(Menu_Form)
        self.upload_menu_button.setGeometry(QtCore.QRect(630, 540, 99, 38))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.upload_menu_button.setFont(font)
        self.upload_menu_button.setStyleSheet("color:gray;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.upload_menu_button.setIconSize(QtCore.QSize(16, 16))
        self.upload_menu_button.setCheckable(False)
        self.upload_menu_button.setObjectName("upload_menu_button")
        self.dish_reco_result_label = MyLabel(Menu_Form)
        self.dish_reco_result_label.setGeometry(QtCore.QRect(260, 50, 160, 120))
        self.dish_reco_result_label.setStyleSheet("border-width: 1px;border-style: solid;border-color: gray;")
        self.dish_reco_result_label.setText("")
        self.dish_reco_result_label.setObjectName("dish_reco_result_label")
        self.save_menu_path_button = QtWidgets.QPushButton(Menu_Form)
        self.save_menu_path_button.setGeometry(QtCore.QRect(630, 390, 99, 38))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.save_menu_path_button.setFont(font)
        self.save_menu_path_button.setStyleSheet("color:gray;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.save_menu_path_button.setIconSize(QtCore.QSize(16, 16))
        self.save_menu_path_button.setCheckable(False)
        self.save_menu_path_button.setObjectName("save_menu_path_button")

        self.retranslateUi(Menu_Form)
        QtCore.QMetaObject.connectSlotsByName(Menu_Form)

    def retranslateUi(self, Menu_Form):
        _translate = QtCore.QCoreApplication.translate
        Menu_Form.setWindowTitle(_translate("Menu_Form", "Form"))
        self.label.setText(_translate("Menu_Form", "     菜品识别画面"))
        self.label_2.setText(_translate("Menu_Form", "  Note"))
        self.clear_menu_txt.setText(_translate("Menu_Form", "Clear"))
        self.save_menu_txt.setText(_translate("Menu_Form", "Save"))
        self.generate_menu_button.setText(_translate("Menu_Form", "生成菜单"))
        self.groupBox.setTitle(_translate("Menu_Form", "Auto"))
        self.auto_mode.setText(_translate("Menu_Form", "自动模式"))
        self.label_4.setText(_translate("Menu_Form", "移动间距："))
        self.label_3.setText(_translate("Menu_Form", "菜品数量："))
        self.start_scan_button.setText(_translate("Menu_Form", "开始扫描"))
        self.groupBox_2.setTitle(_translate("Menu_Form", "Manual"))
        self.manual_mode.setText(_translate("Menu_Form", "手动模式"))
        self.car_forward_copy.setText(_translate("Menu_Form", "Car++"))
        self.car_back_copy.setText(_translate("Menu_Form", "Car--"))
        self.reco_dish_button.setText(_translate("Menu_Form", "识别"))
        self.label_5.setText(_translate("Menu_Form", "菜品位置："))
        self.save_menu_button.setText(_translate("Menu_Form", "保存菜单"))
        self.upload_menu_button.setText(_translate("Menu_Form", "上传菜单"))
        self.save_menu_path_button.setText(_translate("Menu_Form", "PATH"))

from Custom_Control import Car_Backward_button, Car_Forward_button, MyLabel
