# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Initial_work.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Initial_Form(object):
    def setupUi(self, Initial_Form):
        Initial_Form.setObjectName("Initial_Form")
        Initial_Form.resize(755, 600)
        self.label_2 = QtWidgets.QLabel(Initial_Form)
        self.label_2.setGeometry(QtCore.QRect(340, 370, 101, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("color:white;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.label_2.setObjectName("label_2")
        self.groupBox = QtWidgets.QGroupBox(Initial_Form)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 271, 161))
        self.groupBox.setObjectName("groupBox")
        self.Led = MyLed(self.groupBox)
        self.Led.setGeometry(QtCore.QRect(150, 20, 99, 27))
        self.Led.setObjectName("Led")
        self.sys_end = QtWidgets.QPushButton(self.groupBox)
        self.sys_end.setGeometry(QtCore.QRect(10, 90, 99, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.sys_end.setFont(font)
        self.sys_end.setStyleSheet("color:gray;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.sys_end.setObjectName("sys_end")
        self.sys_start = QtWidgets.QPushButton(self.groupBox)
        self.sys_start.setGeometry(QtCore.QRect(10, 30, 99, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.sys_start.setFont(font)
        self.sys_start.setStyleSheet("color:rgb(255,96,96);border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.sys_start.setObjectName("sys_start")
        self.start_with_car_power_button = QtWidgets.QRadioButton(self.groupBox)
        self.start_with_car_power_button.setGeometry(QtCore.QRect(160, 110, 101, 31))
        self.start_with_car_power_button.setObjectName("start_with_car_power_button")
        self.aruco_label = QtWidgets.QLabel(Initial_Form)
        self.aruco_label.setGeometry(QtCore.QRect(330, 50, 400, 300))
        self.aruco_label.setStyleSheet("border-width: 2px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.aruco_label.setText("")
        self.aruco_label.setObjectName("aruco_label")
        self.move_control = QtWidgets.QGroupBox(Initial_Form)
        self.move_control.setGeometry(QtCore.QRect(30, 210, 261, 221))
        self.move_control.setStyleSheet("")
        self.move_control.setObjectName("move_control")
        self.car_forward = Car_Forward_button(self.move_control)
        self.car_forward.setGeometry(QtCore.QRect(20, 130, 99, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.car_forward.setFont(font)
        self.car_forward.setStyleSheet("color:gray;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.car_forward.setObjectName("car_forward")
        self.convey_back = Convey_Backward_button(self.move_control)
        self.convey_back.setGeometry(QtCore.QRect(140, 80, 99, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.convey_back.setFont(font)
        self.convey_back.setStyleSheet("color:gray;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.convey_back.setObjectName("convey_back")
        self.convey_forward = Convey_Forward_button(self.move_control)
        self.convey_forward.setGeometry(QtCore.QRect(20, 80, 99, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.convey_forward.setFont(font)
        self.convey_forward.setStyleSheet("color:gray;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.convey_forward.setObjectName("convey_forward")
        self.car_back = Car_Backward_button(self.move_control)
        self.car_back.setGeometry(QtCore.QRect(140, 130, 99, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.car_back.setFont(font)
        self.car_back.setStyleSheet("color:gray;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.car_back.setObjectName("car_back")
        self.power_switch = QtWidgets.QPushButton(self.move_control)
        self.power_switch.setGeometry(QtCore.QRect(20, 30, 99, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.power_switch.setFont(font)
        self.power_switch.setStyleSheet("color:rgb(178,34,34);border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.power_switch.setObjectName("power_switch")
        self.drop_bowl = QtWidgets.QPushButton(self.move_control)
        self.drop_bowl.setGeometry(QtCore.QRect(20, 180, 221, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.drop_bowl.setFont(font)
        self.drop_bowl.setStyleSheet("color:lightblue;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.drop_bowl.setObjectName("drop_bowl")
        self.power_led = MyLed(self.move_control)
        self.power_led.setGeometry(QtCore.QRect(140, 20, 99, 27))
        self.power_led.setObjectName("power_led")
        self.Initial_messgae_txt = QtWidgets.QTextBrowser(Initial_Form)
        self.Initial_messgae_txt.setGeometry(QtCore.QRect(330, 411, 401, 171))
        self.Initial_messgae_txt.setObjectName("Initial_messgae_txt")
        self.label = QtWidgets.QLabel(Initial_Form)
        self.label.setGeometry(QtCore.QRect(490, 10, 101, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("color:white;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.label.setObjectName("label")
        self.clear_initial_txt = QtWidgets.QPushButton(Initial_Form)
        self.clear_initial_txt.setGeometry(QtCore.QRect(480, 370, 101, 30))
        self.clear_initial_txt.setStyleSheet("color:white;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.clear_initial_txt.setObjectName("clear_initial_txt")
        self.save_initial_txt = QtWidgets.QPushButton(Initial_Form)
        self.save_initial_txt.setGeometry(QtCore.QRect(620, 370, 101, 30))
        self.save_initial_txt.setStyleSheet("color:white;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.save_initial_txt.setObjectName("save_initial_txt")
        self.groupBox_2 = QtWidgets.QGroupBox(Initial_Form)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 440, 261, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.UR10_to_zero = QtWidgets.QPushButton(self.groupBox_2)
        self.UR10_to_zero.setGeometry(QtCore.QRect(30, 80, 99, 38))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.UR10_to_zero.setFont(font)
        self.UR10_to_zero.setStyleSheet("color:gray;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.UR10_to_zero.setObjectName("UR10_to_zero")
        self.recognize_mark_button = QtWidgets.QPushButton(self.groupBox_2)
        self.recognize_mark_button.setGeometry(QtCore.QRect(140, 30, 99, 38))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.recognize_mark_button.setFont(font)
        self.recognize_mark_button.setStyleSheet("color:gray;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.recognize_mark_button.setObjectName("recognize_mark_button")
        self.car_to_zero_button = QtWidgets.QPushButton(self.groupBox_2)
        self.car_to_zero_button.setGeometry(QtCore.QRect(140, 80, 99, 38))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.car_to_zero_button.setFont(font)
        self.car_to_zero_button.setStyleSheet("color:gray;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.car_to_zero_button.setObjectName("car_to_zero_button")
        self.UR3_to_zero = QtWidgets.QPushButton(self.groupBox_2)
        self.UR3_to_zero.setGeometry(QtCore.QRect(30, 30, 99, 38))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.UR3_to_zero.setFont(font)
        self.UR3_to_zero.setStyleSheet("color:gray;border-radius: 10px; border: 2px groove gray;border-style: outset;")
        self.UR3_to_zero.setObjectName("UR3_to_zero")

        self.retranslateUi(Initial_Form)
        QtCore.QMetaObject.connectSlotsByName(Initial_Form)

    def retranslateUi(self, Initial_Form):
        _translate = QtCore.QCoreApplication.translate
        Initial_Form.setWindowTitle(_translate("Initial_Form", "Form"))
        self.label_2.setText(_translate("Initial_Form", "     Note"))
        self.groupBox.setTitle(_translate("Initial_Form", "启动"))
        self.Led.setText(_translate("Initial_Form", "PushButton"))
        self.sys_end.setText(_translate("Initial_Form", "END"))
        self.sys_start.setText(_translate("Initial_Form", "START"))
        self.start_with_car_power_button.setText(_translate("Initial_Form", "小车上电"))
        self.move_control.setTitle(_translate("Initial_Form", "功能测试"))
        self.car_forward.setText(_translate("Initial_Form", "Car++"))
        self.convey_back.setText(_translate("Initial_Form", "Convey--"))
        self.convey_forward.setText(_translate("Initial_Form", "Convey++"))
        self.car_back.setText(_translate("Initial_Form", "Car--"))
        self.power_switch.setText(_translate("Initial_Form", "power_on"))
        self.drop_bowl.setText(_translate("Initial_Form", "drop bowl"))
        self.power_led.setText(_translate("Initial_Form", "PushButton"))
        self.label.setText(_translate("Initial_Form", "     相机画面"))
        self.clear_initial_txt.setText(_translate("Initial_Form", "Clear"))
        self.save_initial_txt.setText(_translate("Initial_Form", "Save"))
        self.groupBox_2.setTitle(_translate("Initial_Form", "复位"))
        self.UR10_to_zero.setText(_translate("Initial_Form", "UR10复位"))
        self.recognize_mark_button.setText(_translate("Initial_Form", "识别标签"))
        self.car_to_zero_button.setText(_translate("Initial_Form", "小车回零"))
        self.UR3_to_zero.setText(_translate("Initial_Form", "UR3复位"))

from Custom_Control import Car_Backward_button, Car_Forward_button, Convey_Backward_button, Convey_Forward_button, MyLed
