set(_CATKIN_CURRENT_PACKAGE "ur3ur10car")
set(ur3ur10car_VERSION "1.0.0")
set(ur3ur10car_MAINTAINER " <TODO@email.com>")
set(ur3ur10car_PACKAGE_FORMAT "2")
set(ur3ur10car_BUILD_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher" "gazebo")
set(ur3ur10car_BUILD_EXPORT_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher" "gazebo")
set(ur3ur10car_BUILDTOOL_DEPENDS "catkin")
set(ur3ur10car_BUILDTOOL_EXPORT_DEPENDS )
set(ur3ur10car_EXEC_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher" "gazebo")
set(ur3ur10car_RUN_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher" "gazebo")
set(ur3ur10car_TEST_DEPENDS )
set(ur3ur10car_DOC_DEPENDS )
set(ur3ur10car_URL_WEBSITE "")
set(ur3ur10car_URL_BUGTRACKER "")
set(ur3ur10car_URL_REPOSITORY "")
set(ur3ur10car_DEPRECATED "")